### PR TITLE
Formatted code to PEP8 standard

### PR DESCRIPTION
**Pull request by supersonic1999**
Nothing major. Installed a linter in my text editor to show PEP8 violations.

### CODE REVIEW

**Comment by psolin** [comment]
Thanks for this. I have been using Sublime Text for Mac for years which has been really basic, and I can't get PEP8 formatting working. I'm going to up my game soon.

**Comment by supersonic1999** [comment]
You can just read up on the standard manually here: https://www.python.org/dev/peps/pep-0008/
but that's a bit time consuming.  What text editor do you use to do python on mac?

**Comment by psolin** [comment]
Sublime Text. Looking into Pycharm + Kite now.

**Comment by supersonic1999** [comment]
I use sublime text too!, 
Installed sublimelinter and sublimelinter-pycodestyle from inside sublime, then pip install pycodestyle in bash

**Comment by psolin** [comment]
I just posted an update through PyCharm IDE and it seems to have PEP8 built in with a lot of other features. I would recommend that you give it a shot.

I didn't install Kite yet, because they haven't made a version for M1 Macs yet, but it seems very promising.

**Pull request merged**
